[WIP]API with Redux
StudioAquatan/Saffron pull request #122
Opened 2019-02-11 10:47 UTC by taxio

- [ ] Web APIを叩く部分をActionに移行
- [ ] componentからcontainerを切り出して，なるべくFC化する．
- [x] Web APIのinterfaceが重複化しそうなので切り出してModelを作る 
- [x] API Refactorの追従 ( refs #113 )

2019-02-12 13:40 UTC, pddg requested changes

2019-02-12 13:40 UTC, pddg commented on petals/src/api/util.ts
> +    case 404:
403はないの？

2019-02-12 14:49 UTC, taxio commented
修正した

2019-02-13 03:11 UTC, pddg requested changes

2019-02-13 03:11 UTC, pddg commented on petals/src/api/util.ts
> +      throw new AppErr.ForbiddenError('アクセス権限がありません');
403のエラーメッセージ，今回は複雑だから返す時にメッセージの内容に弾かれた理由をいれるようにしようとしてるんだけど，そこのハンドリングはもうしない？全てこのメッセージで統一する？

2019-02-13 03:29 UTC, taxio commented on petals/src/api/util.ts
> +      throw new AppErr.ForbiddenError('アクセス権限がありません');
基本的にレスポンスに含まれるエラーメッセージを優先したい気持ちはある．フロントでのバリデーションにも限界があるから．
現状はどんなエラーメッセージか返ってくるかよく分かってないから一般的なエラーメッセージをここで定義してるだけ．
ここの細かいエラーハンドリングはアプリがある程度出来上がってからの作り込みになると思う．

2019-02-13 03:29 UTC, pddg commented on petals/src/api/util.ts
> +      throw new AppErr.ForbiddenError('アクセス権限がありません');
了解

2019-02-13 03:29 UTC, pddg approved these changes
LGTM

2019-02-13 03:30 UTC, merged