Activation
StudioAquatan/Saffron pull request #59
Opened 2019-01-01 13:15 UTC by taxio

ロジックはできたけどデザインは適当です．
どうせあとで変えるんだからいいよね...

close #58

2019-01-01 14:54 UTC, pddg requested changes
react-router-domがURL Fragmentのルーティングに対応していない…

2019-01-01 14:54 UTC, pddg commented on petals/src/App.tsx
> +          <Route exact={true} path="/activate/:uid/:token" component={Activation} />
アクティベーションのURLは`/#/activate/:uid/:token`になる

2019-01-01 14:54 UTC, pddg commented on petals/src/App.tsx
> +          <Route exact={true} path="/activate/:uid/:token" component={Activation} />
これはリファラにフラグメントが記録されないことを利用して，アクセスログにトークンを残さないため．

2019-01-02 09:01 UTC, taxio commented
あ，動いてない．ちょっと待って．

2019-01-02 09:09 UTC, pddg commented
OKになったら`do not merge`外して

2019-01-02 10:24 UTC, taxio commented
修正完了

2019-01-02 10:34 UTC, pddg approved these changes
LGTM

2019-01-02 10:35 UTC, merged